name: NPM Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: dist-package
          path: dist/package.json
  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/download-artifact@v1
        with:
          name: dist-package
          path: dist/
      - id: version
        run: |
          VERSION=$(node -p "require('./dist/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - id: changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}
          DATE=$(grep "\[$VERSION\]" CHANGELOG.md | head -n 1 | sed -E 's/.*\(([0-9]{4}-[0-9]{2}-[0-9]{2})\).*/\1/')
          CHANGELOG="${VERSION}-${DATE}"
          CHANGELOG=$(echo "$CHANGELOG" | sed 's/\.//g' | sed -E 's/[ \t]+/-/g')
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
      - run: |
          VERSION=${{ steps.version.outputs.version }}
          CHANGELOG=${{ steps.changelog.outputs.changelog }}
          curl -X POST -H 'Content-Type: application/json' \
            -d "{
              \"channel\": \"steroids-nest\",
              \"text\": \"#newVersion\n${{ github.repository }} ${VERSION}\n[Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md#${CHANGELOG})\"
            }" ${{ secrets.MATTERMOST_WEBHOOK_URL }}
